version: '3.9'
services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - "C:/Users/abrah/Desktop/Proyecto PHP:/var/www/html"
  bd:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    volumes:
      - bbdd_datos:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bd
      PMA_USER: root
      PMA_PASSWORD: root
volumes:
  bbdd_datos: